#!/usr/bin/env python3
"""
Build the website by injecting a footer with stats directly into the heatmap HTML.
No iframe — the Folium map is the page, with a footer overlay.
"""

import json
import os


def build_website():
    """Build index.html by injecting footer into heatmap.html"""

    # Load stats
    stats = {}
    if os.path.exists('stats.json'):
        with open('stats.json', 'r') as f:
            stats = json.load(f)

    # Read heatmap HTML (generated by Folium + mobile fixes)
    if not os.path.exists('heatmap.html'):
        print("Error: heatmap.html not found! Run generate_heatmap.py first.")
        return

    with open('heatmap.html', 'r') as f:
        html = f.read()

    # Build footer content from stats
    total = stats.get('total_activities', 0)
    last = stats.get('last_activity')

    last_activity_html = ''
    if last:
        last_activity_html = f'''
        <span class="footer-separator">&middot;</span>
        <div class="footer-item">
            <span class="footer-label">Latest:</span>
            <span class="footer-value">{last['name']}</span>
        </div>
        <span class="footer-separator">&middot;</span>
        <div class="footer-item">
            <span class="footer-value">{last['date']}</span>
        </div>'''

    footer_injection = f'''
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400&display=swap" rel="stylesheet">
<style>
.heatmap-footer {{
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background: rgba(250, 250, 250, 0.95);
    -webkit-backdrop-filter: blur(8px);
    backdrop-filter: blur(8px);
    padding: 14px 28px;
    padding-bottom: max(14px, env(safe-area-inset-bottom));
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 32px;
    border-top: 1px solid #d4d4d4;
    font-size: 13px;
    font-family: 'Space Grotesk', -apple-system, BlinkMacSystemFont, sans-serif;
    letter-spacing: 0.02em;
    z-index: 1000;
}}
.heatmap-footer .footer-item {{ display: flex; align-items: center; gap: 6px; }}
.heatmap-footer .footer-label {{ font-weight: 400; color: #171717; }}
.heatmap-footer .footer-value {{ font-weight: 300; color: #737373; }}
.heatmap-footer .footer-separator {{ color: #d4d4d4; }}
@media (max-width: 768px) {{
    .heatmap-footer {{
        padding: 10px 18px;
        padding-bottom: max(10px, env(safe-area-inset-bottom));
        font-size: 11px;
        gap: 16px;
    }}
    .heatmap-footer .footer-separator {{ display: none; }}
    .heatmap-footer {{ flex-direction: column; gap: 4px; }}
}}
</style>
<div class="heatmap-footer">
    <div class="footer-item">
        <span class="footer-label">Jesse Alloy</span>
    </div>
    <span class="footer-separator">&middot;</span>
    <div class="footer-item">
        <span class="footer-value">{total} activities</span>
    </div>
    {last_activity_html}
</div>
'''

    # Inject footer before </body>
    html = html.replace('</body>', footer_injection + '</body>')

    # Update the page title
    html = html.replace('<title>Make this Notebook Trusted to load map: File -> Trust Notebook</title>',
                        '<title>Activity Heatmap</title>')

    # Save as index.html
    with open('index.html', 'w') as f:
        f.write(html)

    print("✓ Website built: index.html (direct embed, no iframe)")
    print("\nFiles needed for deployment:")
    print("  - index.html")


if __name__ == "__main__":
    build_website()
